[buildPlans.iosevka-term-jbms]
family = "Iosevka Term JBMS"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-term-jbms.variants]
  inherits = "ss14" # JetBrains Mono Style

    [buildPlans.iosevka-term-jbms.variants.design]
    g = "single-storey-serifless"

  [buildPlans.iosevka-term-jbms.ligations]
  inherits = "haskell"
