[buildPlans.IosevkaTermJBMS]
family = "Iosevka Term JBMS"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaTermJBMS.variants]
  inherits = "ss14" # JetBrains Mono Style

    [buildPlans.IosevkaTermJBMS.variants.design]
    g = "single-storey-serifless"

  [buildPlans.IosevkaTermJBMS.ligations]
  inherits = "haskell"
